SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE   VIEW [dbo].[VWS_ICMS_Aliquotas] AS
SELECT 
  O.UFID Emi_UFID,
  O.UF Emi_UF, 
  D.UFID Dest_UFID,
  D.UF Dest_UF, 
  CASE 
    WHEN O.UF=D.UF AND O.UF IN ('RJ') THEN 20.00
	WHEN O.UF=D.UF AND O.UF IN ('RO') THEN 20.00
	WHEN O.UF=D.UF AND O.UF IN ('ES', 'GO', 'MS', 'MT', 'PA', 'RR') THEN 17.00
    WHEN O.UF=D.UF THEN O.ICMSInt
	WHEN O.UF<>D.UF AND  O.UF IN ('MG', 'PR', 'RJ', 'SC', 'SP') AND D.UF IN ('MG', 'PR', 'RJ', 'SC', 'SP') THEN 12.00
	WHEN O.UF<>D.UF AND  O.UF IN ('MG', 'PR', 'RJ', 'SC', 'SP') THEN 7.00
	ELSE 12
  END ICMS
FROM dbo.LkpUF0 O, dbo.LkpUF0 D
WHERE O.UFID<>99 AND D.UFID<>99


GO
