SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE   VIEW [dbo].[VWS_Movimento_Totais] AS

SELECT 
  MI.Chave,
  MI.UnidadeID,
  COUNT(*) AS Itens,
  CONVERT(DECIMAL(18,3), SUM(MI.Quantidade)) AS Quantidade,
  CONVERT(DECIMAL(18,6), SUM(MI.Ps_Bruto)) AS Ps_Bruto,
  CONVERT(DECIMAL(18,6), SUM(MI.Ps_Liquido)) AS Ps_Liquido,
  CONVERT(DECIMAL(18,6), SUM(MI.Volume)) AS Volume,

  -- Valores
  CONVERT(DECIMAL(18,2), SUM(MI.VL_Estoque)) AS VL_Estoque,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_Item)) AS VL_Item,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_CustoBruto)) AS VL_CustoBruto,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_CustoMedio)) AS VL_CustoMedio,
  CONVERT(DECIMAL(6,4), SUM(MI.VL_Desconto) / NULLIF(SUM(MI.VL_Item), 0) * 100) AS Desconto,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_Desconto)) AS VL_Desconto,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_Liquido)) AS VL_Liquido,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_Frete)) AS VL_Frete,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_Seguro)) AS VL_Seguro,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_Outro)) AS VL_Outro,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_Anexo)) AS VL_Anexo,

  -- Comissão
  CONVERT(DECIMAL(18,2), SUM(MI.VL_Liquido)) AS BC_Comissao,
  CONVERT(DECIMAL(6,4), SUM(MI.VL_Comissao) / NULLIF(SUM(MI.VL_Liquido), 0) * 100) AS Comissao,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_Comissao)) AS VL_Comissao,

  -- Tributos
  CONVERT(DECIMAL(18,2), SUM(MI.BC_ICMS)) AS BC_ICMS,
  CONVERT(DECIMAL(18,2), SUM(MI.Vl_ICMS)) AS Vl_ICMS,
  CONVERT(DECIMAL(18,2), SUM(MI.BC_IPI)) AS BC_IPI,
  CONVERT(DECIMAL(18,2), SUM(MI.Vl_IPI)) AS Vl_IPI,
  CONVERT(DECIMAL(18,2), SUM(MI.BC_ICMSSub)) AS BC_ICMSSub,
  CONVERT(DECIMAL(18,2), SUM(MI.Vl_ICMSSUB)) AS Vl_ICMSSUB,
  CONVERT(DECIMAL(18,2), SUM(MI.BC_ISS)) AS BC_ISS,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_ISS)) AS VL_ISS,
  CONVERT(DECIMAL(18,2), SUM(MI.BC_PIS)) AS BC_PIS,
  CONVERT(DECIMAL(18,2), SUM(MI.Vl_PIS)) AS Vl_PIS,
  CONVERT(DECIMAL(18,2), SUM(MI.BC_COFINS)) AS BC_COFINS,
  CONVERT(DECIMAL(18,2), SUM(MI.Vl_COFINS)) AS Vl_COFINS,

  -- DIFAL
  CONVERT(DECIMAL(18,2), SUM(MI.DIFAL_BC_FCP)) AS DIFAL_BC_FCP,
  CONVERT(DECIMAL(6,4), SUM(MI.DIFAL_Aliq_FCP)) AS DIFAL_Aliq_FCP,
  CONVERT(DECIMAL(18,2), SUM(MI.DIFAL_VL_FCP)) AS DIFAL_VL_FCP,
  CONVERT(DECIMAL(18,2), SUM(MI.DIFAL_BC_ICMSDest)) AS DIFAL_BC_ICMSDest,
  CONVERT(DECIMAL(6,4), SUM(MI.DIFAL_Aliq_ICMSInter)) AS DIFAL_Aliq_ICMSInter,
  CONVERT(DECIMAL(6,4), SUM(MI.DIFAL_Aliq_ICMSDest)) AS DIFAL_Aliq_ICMSDest,
  CONVERT(DECIMAL(6,4), SUM(MI.DIFAL_Partilha) / COUNT(*)) AS DIFAL_Partilha,
  CONVERT(DECIMAL(18,2), SUM(MI.DIFAL_VL_ICMSDest)) AS DIFAL_VL_ICMSDest,
  CONVERT(DECIMAL(18,2), SUM(MI.DIFAL_VL_ICMSRemet)) AS DIFAL_VL_ICMSRemet,

  -- Totais finais
  CONVERT(DECIMAL(18,2), SUM(MI.VL_NF)) AS VL_NF,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_Operacional)) AS VL_Operacional,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_Margem)) AS VL_Margem,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_CustoAquisicao)) AS VL_CustoAquisicao,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_Despesa)) AS VL_Despesa,
  CONVERT(DECIMAL(18,2), SUM(MI.VL_Total)) AS VL_Total

FROM dbo.VWS_Movimento_Item MI
WHERE MI.VL_Total > 0 AND MI.VL_Item > 0
GROUP BY MI.Chave, MI.UnidadeID

UNION ALL

SELECT 
  M.Chave,
  C.UnidadeID,
  1 AS Itens,
  CONVERT(DECIMAL(18,3), 1.000) AS Quantidade,
  CONVERT(DECIMAL(18,6), 0) AS Ps_Bruto,
  CONVERT(DECIMAL(18,6), 0) AS Ps_Liquido,
  CONVERT(DECIMAL(18,6), 0.0000) AS Volume,
  CONVERT(DECIMAL(18,2), C.Total) AS VL_Estoque,
  CONVERT(DECIMAL(18,2), C.Total) AS VL_Item,
  CONVERT(DECIMAL(18,2), C.Total) AS VL_CustoBruto,
  CONVERT(DECIMAL(18,2), C.Total) AS VL_CustoMedio,
  CONVERT(DECIMAL(6,4), 0) AS Desconto,
  CONVERT(DECIMAL(18,2), 0) AS VL_Desconto,
  CONVERT(DECIMAL(18,2), C.Total) AS VL_Liquido,
  CONVERT(DECIMAL(18,2), C.Total) AS VL_Frete,
  CONVERT(DECIMAL(18,2), 0) AS VL_Seguro,
  CONVERT(DECIMAL(18,2), 0) AS VL_Outro,
  CONVERT(DECIMAL(18,2), 0) AS VL_Anexo,
  CONVERT(DECIMAL(18,2), 0) AS BC_Comissao,
  CONVERT(DECIMAL(6,4), 0) AS Comissao,
  CONVERT(DECIMAL(18,2), 0) AS VL_Comissao,
  CONVERT(DECIMAL(18,2), C.BC_ICMS) AS BC_ICMS,
  CONVERT(DECIMAL(18,2), C.BC_ICMS * C.ICMS / 100) AS Vl_ICMS,
  CONVERT(DECIMAL(18,2), 0) AS BC_IPI,
  CONVERT(DECIMAL(18,2), 0) AS Vl_IPI,
  CONVERT(DECIMAL(18,2), 0) AS BC_ICMSSub,
  CONVERT(DECIMAL(18,2), 0) AS Vl_ICMSSUB,
  CONVERT(DECIMAL(18,2), 0) AS BC_ISS,
  CONVERT(DECIMAL(18,2), 0) AS VL_ISS,
  CONVERT(DECIMAL(18,2), C.BC_PIS) AS BC_PIS,
  CONVERT(DECIMAL(18,2), C.BC_PIS * C.ALIQ_PIS / 100) AS Vl_PIS,
  CONVERT(DECIMAL(18,2), C.BC_COFINS) AS BC_COFINS,
  CONVERT(DECIMAL(18,2), C.BC_COFINS * C.ALIQ_COFINS / 100) AS Vl_COFINS,
  CONVERT(DECIMAL(18,2), 0) AS DIFAL_BC_FCP,
  CONVERT(DECIMAL(6,4), 0) AS DIFAL_Aliq_FCP,
  CONVERT(DECIMAL(18,2), 0) AS DIFAL_VL_FCP,
  CONVERT(DECIMAL(18,2), 0) AS DIFAL_BC_ICMSDest,
  CONVERT(DECIMAL(6,4), 0) AS DIFAL_Aliq_ICMSInter,
  CONVERT(DECIMAL(6,4), 0) AS DIFAL_Aliq_ICMSDest,
  CONVERT(DECIMAL(6,4), 0) AS DIFAL_Partilha,
  CONVERT(DECIMAL(18,2), 0) AS DIFAL_VL_ICMSDest,
  CONVERT(DECIMAL(18,2), 0) AS DIFAL_VL_ICMSRemet,
  CONVERT(DECIMAL(18,2), C.Total) AS VL_NF,
  CONVERT(DECIMAL(18,2), 0) AS VL_Operacional,
  CONVERT(DECIMAL(18,2), 0) AS VL_Margem,
  CONVERT(DECIMAL(18,2), C.Total) AS VL_CustoAquisicao,
  CONVERT(DECIMAL(18,2), 0) AS VL_Despesa,
  CONVERT(DECIMAL(18,2), C.Total) AS VL_Total

FROM dbo.CTE_Conhecimento C
JOIN dbo.MovNota0 M ON M.UnidadeID = C.UnidadeID AND M.TipoID = C.TipoID AND M.Nota = C.Nota
GO
