CREATE TABLE [dbo].[COM_ITE_VEIC]
(
[ItemID] [int] NOT NULL,
[PotenciaMotor] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
[CilindradasCM3] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
[CombustivelID] [tinyint] NOT NULL,
[CMKG] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
[EntreEixos] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
[RENAVAM] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
[TipoID] [tinyint] NOT NULL,
[EspecieID] [tinyint] NOT NULL
)
GO
ALTER TABLE [dbo].[COM_ITE_VEIC] ADD CONSTRAINT [PK_PrdVeic0] PRIMARY KEY CLUSTERED ([ItemID])
GO
ALTER TABLE [dbo].[COM_ITE_VEIC] ADD CONSTRAINT [FK_COM_ITE_VEIC_COM_ITE_PRD] FOREIGN KEY ([ItemID]) REFERENCES [dbo].[COM_ITE_PRD] ([ItemID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[COM_ITE_VEIC] ADD CONSTRAINT [FK_PrdVeic0_LKPTipoCombustivel] FOREIGN KEY ([CombustivelID]) REFERENCES [dbo].[LKPTipoCombustivel] ([CombustivelID]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[COM_ITE_VEIC] ADD CONSTRAINT [FK_PrdVeic0_LKPVeic0] FOREIGN KEY ([TipoID]) REFERENCES [dbo].[LKPVeic0] ([TipoID]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[COM_ITE_VEIC] ADD CONSTRAINT [FK_PrdVeic0_LKPVeic1] FOREIGN KEY ([EspecieID]) REFERENCES [dbo].[LKPVeic1] ([EspecieID]) ON UPDATE CASCADE
GO
