CREATE TABLE [dbo].[FIS_MDFe_NFe]
(
[FIS_MDFe_ID] [int] NOT NULL,
[NFE] [char] (44) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
[CidadeID] [int] NOT NULL
)
GO
ALTER TABLE [dbo].[FIS_MDFe_NFe] ADD CONSTRAINT [PK_FIS_MDFe_NFe_1] PRIMARY KEY CLUSTERED ([FIS_MDFe_ID], [NFE])
GO
ALTER TABLE [dbo].[FIS_MDFe_NFe] ADD CONSTRAINT [FK_FIS_MDFe_NFe_CadCida0] FOREIGN KEY ([CidadeID]) REFERENCES [dbo].[CadCida0] ([CidadeID])
GO
ALTER TABLE [dbo].[FIS_MDFe_NFe] ADD CONSTRAINT [FK_FIS_MDFe_NFe_FIS_MDFe] FOREIGN KEY ([FIS_MDFe_ID]) REFERENCES [dbo].[FIS_MDFe] ([FIS_MDFe_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
