CREATE TABLE [dbo].[FIS_ITE_GRP_CAD]
(
[GFID] [tinyint] NOT NULL,
[Grupo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL
)
GO
ALTER TABLE [dbo].[FIS_ITE_GRP_CAD] ADD CONSTRAINT [PK_FIS_PRD_GRP_CAD] PRIMARY KEY CLUSTERED ([GFID])
GO
