CREATE TABLE [dbo].[FIS_MDFe_Municipios]
(
[FIS_MDFe_ID] [int] NOT NULL,
[CidadeID] [int] NOT NULL
)
GO
ALTER TABLE [dbo].[FIS_MDFe_Municipios] ADD CONSTRAINT [PK_FIS_MDFe_Municipios] PRIMARY KEY CLUSTERED ([FIS_MDFe_ID], [CidadeID])
GO
ALTER TABLE [dbo].[FIS_MDFe_Municipios] ADD CONSTRAINT [FK_FIS_MDFe_Municipios_CadCida0] FOREIGN KEY ([CidadeID]) REFERENCES [dbo].[CadCida0] ([CidadeID])
GO
ALTER TABLE [dbo].[FIS_MDFe_Municipios] ADD CONSTRAINT [FK_FIS_MDFe_Municipios_FIS_MDFe] FOREIGN KEY ([FIS_MDFe_ID]) REFERENCES [dbo].[FIS_MDFe] ([FIS_MDFe_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
