CREATE TABLE [dbo].[COM_ITE_PRC]
(
[UnidadeID] [tinyint] NOT NULL,
[ItemID] [int] NOT NULL,
[PrecoID] [tinyint] NOT NULL,
[Valor] [decimal] (18, 10) NOT NULL
)
GO
ALTER TABLE [dbo].[COM_ITE_PRC] ADD CONSTRAINT [PK_ProdPrec0] PRIMARY KEY CLUSTERED ([UnidadeID], [ItemID], [PrecoID])
GO
CREATE NONCLUSTERED INDEX [_dta_index_COM_ITE_PRC_31_2135639347__K3_K2_K1_4] ON [dbo].[COM_ITE_PRC] ([PrecoID], [ItemID], [UnidadeID]) INCLUDE ([Valor])
GO
ALTER TABLE [dbo].[COM_ITE_PRC] ADD CONSTRAINT [FK_COM_ITE_PRC_COM_ITE_UND] FOREIGN KEY ([UnidadeID], [ItemID]) REFERENCES [dbo].[COM_ITE_UND] ([UnidadeID], [ItemID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[COM_ITE_PRC] ADD CONSTRAINT [FK_ProdPrec0_SysPrec0] FOREIGN KEY ([PrecoID]) REFERENCES [dbo].[COM_PRC_CAD] ([PrecoID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
EXEC sp_bindefault N'[dbo].[DF_Zero]', N'[dbo].[COM_ITE_PRC].[Valor]'
GO
