CREATE TABLE [dbo].[UND_PES]
(
[ID] [tinyint] NOT NULL,
[UnidadeID] [tinyint] NOT NULL,
[PessoaID] [int] NOT NULL
)
GO
ALTER TABLE [dbo].[UND_PES] ADD CONSTRAINT [PK_UND_PES] PRIMARY KEY CLUSTERED ([ID], [UnidadeID])
GO
ALTER TABLE [dbo].[UND_PES] ADD CONSTRAINT [FK_UND_PES_CadPess0] FOREIGN KEY ([PessoaID]) REFERENCES [dbo].[CadPess0] ([PessoaID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[UND_PES] ADD CONSTRAINT [FK_UND_PES_FIS_Unidade] FOREIGN KEY ([UnidadeID]) REFERENCES [dbo].[FIS_Unidade] ([UnidadeID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
