CREATE TABLE [dbo].[FIS_CFOP]
(
[CFOP] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
[Descricao] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL
)
GO
ALTER TABLE [dbo].[FIS_CFOP] ADD CONSTRAINT [PK_FIS_CFOP] PRIMARY KEY CLUSTERED ([CFOP])
GO
