CREATE TABLE [dbo].[PES_IE]
(
[UFID] [tinyint] NOT NULL,
[IE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
[PessoaID] [int] NOT NULL
)
GO
ALTER TABLE [dbo].[PES_IE] ADD CONSTRAINT [PK_PES_IE] PRIMARY KEY CLUSTERED ([UFID], [IE])
GO
ALTER TABLE [dbo].[PES_IE] ADD CONSTRAINT [FK_PES_IE_CadPess0] FOREIGN KEY ([PessoaID]) REFERENCES [dbo].[CadPess0] ([PessoaID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[PES_IE] ADD CONSTRAINT [FK_PES_IE_LkpUF0] FOREIGN KEY ([UFID]) REFERENCES [dbo].[LkpUF0] ([UFID])
GO
