CREATE TABLE [dbo].[DFe_MOV]
(
[Chave] [char] (14) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
[TipoID] [tinyint] NOT NULL,
[ID] [char] (44) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL
)
GO
ALTER TABLE [dbo].[DFe_MOV] ADD CONSTRAINT [PK_DFe_MOV] PRIMARY KEY CLUSTERED ([Chave], [TipoID])
GO
CREATE NONCLUSTERED INDEX [ix_id] ON [dbo].[DFe_MOV] ([ID])
GO
ALTER TABLE [dbo].[DFe_MOV] ADD CONSTRAINT [FK_DFe_MOV_DFe_XML] FOREIGN KEY ([ID]) REFERENCES [dbo].[DFe_XML] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DFe_MOV] ADD CONSTRAINT [FK_DFe_MOV_MovFisc0] FOREIGN KEY ([Chave]) REFERENCES [dbo].[MovFisc0] ([Chave]) ON DELETE CASCADE ON UPDATE CASCADE
GO
