CREATE TABLE [dbo].[FIS_MDFe_Condutor]
(
[FIS_MDFe_ID] [int] NOT NULL,
[CPF] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
[Nome] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL
)
GO
ALTER TABLE [dbo].[FIS_MDFe_Condutor] ADD CONSTRAINT [PK_FIS_MDFe_Condutor_1] PRIMARY KEY CLUSTERED ([FIS_MDFe_ID], [CPF])
GO
ALTER TABLE [dbo].[FIS_MDFe_Condutor] ADD CONSTRAINT [FK_FIS_MDFe_Condutor_FIS_MDFe_Rodo1] FOREIGN KEY ([FIS_MDFe_ID]) REFERENCES [dbo].[FIS_MDFe_Rodo] ([FIS_MDFe_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
