CREATE TABLE [dbo].[CadCida0]
(
[CidadeID] [int] NOT NULL,
[Cidade] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
[UFID] [tinyint] NOT NULL
)
GO
ALTER TABLE [dbo].[CadCida0] ADD CONSTRAINT [PK_CADCIDA0] PRIMARY KEY NONCLUSTERED ([CidadeID])
GO
CREATE NONCLUSTERED INDEX [IX_CadCida0] ON [dbo].[CadCida0] ([CidadeID], [UFID])
GO
ALTER TABLE [dbo].[CadCida0] WITH NOCHECK ADD CONSTRAINT [FK_CadCida0_LkpUF0] FOREIGN KEY ([UFID]) REFERENCES [dbo].[LkpUF0] ([UFID]) ON UPDATE CASCADE
GO
