CREATE TABLE [dbo].[FIS_MDFe_Rodo]
(
[FIS_MDFe_ID] [int] NOT NULL,
[RNTRC] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
[Placa] [char] (7) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
[UFID] [tinyint] NOT NULL,
[Tara] [int] NOT NULL,
[tpRod] [tinyint] NOT NULL,
[TpCar] [tinyint] NOT NULL
)
GO
ALTER TABLE [dbo].[FIS_MDFe_Rodo] ADD CONSTRAINT [PK_FIS_MDFe_Rodo_1] PRIMARY KEY CLUSTERED ([FIS_MDFe_ID])
GO
ALTER TABLE [dbo].[FIS_MDFe_Rodo] ADD CONSTRAINT [FK_FIS_MDFe_Rodo_FIS_MDFe1] FOREIGN KEY ([FIS_MDFe_ID]) REFERENCES [dbo].[FIS_MDFe] ([FIS_MDFe_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
