CREATE TABLE [dbo].[PES_Rotulo]
(
[PessoaID] [int] NOT NULL,
[PES_DOC_ID] [tinyint] NOT NULL,
[Rotulo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL
)
GO
ALTER TABLE [dbo].[PES_Rotulo] ADD CONSTRAINT [PK_PES_Rotulo] PRIMARY KEY CLUSTERED ([PessoaID], [PES_DOC_ID])
GO
ALTER TABLE [dbo].[PES_Rotulo] ADD CONSTRAINT [FK_PES_Rotulo_CadPess0] FOREIGN KEY ([PessoaID]) REFERENCES [dbo].[CadPess0] ([PessoaID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[PES_Rotulo] ADD CONSTRAINT [FK_PES_Rotulo_PES_Rotulo_+CAD] FOREIGN KEY ([PES_DOC_ID]) REFERENCES [dbo].[PES_Rotulo_CAD] ([PES_Rotulo_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
